### ISSUE TITLE
TypeError: unsupported operand type(s) for |: 'type' and 'NoneType'

### ISSUE THREAD

**Issue by RasmusB** [agmmnn/textual-filedrop#1]
Hello,

I'm tyring to run the fullscreen.py and the hidden.py examples, but I get stuck on this error:

```
Traceback (most recent call last):
  File "fullscreen.py", line 2, in <module>
    from textual_filedrop import FileDrop
  File "C:\Users\Rasmus\AppData\Local\Programs\Python\Python38\lib\site-packages\textual_filedrop\__init__.py", line 1, in <module>
    from ._filedrop import FileDrop
  File "C:\Users\Rasmus\AppData\Local\Programs\Python\Python38\lib\site-packages\textual_filedrop\_filedrop.py", line 15, in <module>
    class FileDrop(Widget, can_focus=True, can_focus_children=False):
  File "C:\Users\Rasmus\AppData\Local\Programs\Python\Python38\lib\site-packages\textual_filedrop\_filedrop.py", line 33, in FileDrop
    name: str | None = None,
TypeError: unsupported operand type(s) for |: 'type' and 'NoneType'
```

Example files are unmodified. OS is Windows 10, Python version string is:
`Python 3.8.1 (tags/v3.8.1:1b293b6, Dec 18 2019, 23:11:46) [MSC v.1916 64 bit (AMD64)] on win32`

Am I doing something wrong? I installed through pip, so any dependencies should have been taken care of.

**Comment by agmmnn** [comment]
Oh it is probably compatibility issue, I'll take a look when I get to the computer.

**Comment by agmmnn** [comment]
https://github.com/agmmnn/textual-filedrop/releases/tag/v0.2.4 - python <3.10 support
